# Import library

In [1]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

# Load dataset

In [2]:
file_path = 'DataCleaningTA.csv'
df = pd.read_csv(file_path)

# Transformasi data

In [3]:
# Mengubah string list menjadi list Python
df['jenis_item'] = df['jenis_item'].apply(eval)

# One-hot encoding terhadap produk
mlb = MultiLabelBinarizer()
produk_encoded = mlb.fit_transform(df['jenis_item'])
produk_df = pd.DataFrame(produk_encoded, columns=mlb.classes_)

# Menambahkan kolom tanggal pembelian dan nomor transaksi
final_df = pd.concat([df['tanggal pembelian'], produk_df], axis=1)
final_df.insert(1, 'transaksi', range(1, len(final_df) + 1))

# Menampilkan seluruh DataFrame
# Pandas default hanya menampilkan 60 baris dan 20 kolom, jadi kita ubah pengaturannya
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# Menampilkan seluruh data
display(final_df)

,tanggal pembelian,transaksi,Aksesoris Buku,Alat Tulis,Buku Anak-Anak,Buku Biografi,Buku Fiksi,Buku Sejarah,Majalah Berita,Majalah Fashion,Majalah Seni,Novel Fiksi Ilmiah,Novel Misteri,Novel Romansa
0,2010-01-01,1,0,1,1,0,1,1,1,1,0,0,0,1
1,2010-03-03,2,0,1,0,0,0,0,0,0,1,0,0,0
2,2010-05-01,3,1,0,0,1,0,0,1,0,0,0,0,1
3,2010-05-01,4,0,0,0,0,0,0,1,1,0,1,1,0
4,2010-05-01,5,0,0,1,0,1,0,0,0,1,1,0,0
5,2010-06-27,6,0,1,1,0,0,1,0,0,0,0,0,0
6,2010-06-27,7,1,0,0,0,0,0,0,0,0,0,0,0
7,2010-08-20,8,0,0,0,0,0,0,0,1,0,0,0,0
8,2010-10-29,9,1,0,0,0,0,0,1,0,1,0,0,1
9,2010-10-29,10,0,1,0,0,0,1,1,1,1,0,0,0
10,2010-10-29,11,1,0,0,1,0,0,1,0,0,1,1,0
11,2010-10-29,12,1,1,0,1,0,0,0,1,0,1,0,1
12,2011-01-20,13,0,0,0,1,0,0,0,0,0,0,0,0
13,2011-03-22,14,0,0,0,0,0,0,0,0,0,0,0,1
14,2011-03-22,15,1,0,0,0,0,0,0,0,0,0,0,0
15,2011-05-17,16,1,0,0,1,0,0,0,0,1,1,0,1
16,2011-05-17,17,1,0,0,0,1,1,1,1,1,1,0,1
17,2011-05-17,18,0,1,0,0,0,0,1,0,0,1,0,0
18,2011-07-27,19,0,1,0,0,0,0,0,0,0,0,0,0
19,2011-08-28,20,0,1,1,0,0,1,0,1,0,0,0,0
20,2011-08-28,21,0,0,1,1,0,0,0,1,0,0,0,1
21,2011-08-28,22,0,0,1,1,0,0,1,1,1,0,0,1
22,2011-08-28,23,0,0,0,0,0,1,1,0,0,0,0,0
23,2011-10-20,24,1,0,0,1,0,0,0,0,0,0,0,0
24,2011-11-23,25,0,0,0,0,0,0,1,0,1,0,0,0
25,2012-01-25,26,0,1,1,0,0,1,0,1,0,0,0,0
26,2012-01-25,27,0,1,0,0,0,1,0,0,0,1,1,0
27,2012-01-25,28,0,1,1,1,1,1,1,1,0,1,0,0
28,2012-01-25,29,1,0,0,0,0,0,0,0,0,0,1,1
29,2012-04-23,30,0,0,0,1,0,0,0,0,0,0,0,0
30,2012-07-31,31,0,1,1,0,0,1,0,0,0,1,0,0
31,2012-07-31,32,1,1,1,1,0,1,0,1,1,1,0,0
32,2012-07-31,33,0,0,1,0,1,0,1,0,0,0,0,0
33,2012-07-31,34,1,1,1,1,0,0,1,0,0,1,1,1
34,2012-07-31,35,0,0,0,0,0,0,0,0,0,0,0,1
35,2012-07-31,36,0,1,0,1,1,0,1,1,0,1,1,0
36,2012-07-31,37,1,1,0,0,0,1,0,0,1,0,0,0
37,2012-09-30,38,1,0,0,0,0,0,0,0,0,0,0,0
38,2012-09-30,39,0,0,0,0,0,0,0,0,1,1,1,1
39,2012-09-30,40,0,1,1,1,0,0,1,1,1,1,0,0
40,2012-10-24,41,0,0,0,0,0,0,1,1,0,1,0,1
41,2012-10-24,42,0,1,0,1,1,1,1,1,1,1,0,0
42,2012-10-24,43,1,0,0,0,0,0,0,0,0,0,0,0
43,2012-12-21,44,0,0,1,0,0,0,0,0,0,0,0,0
44,2012-12-21,45,0,1,1,0,1,1,1,0,1,0,0,0
45,2013-03-10,46,0,0,0,0,0,0,1,1,1,0,0,0
46,2013-04-07,47,1,0,0,0,1,0,0,0,0,1,0,0
47,2013-04-07,48,0,1,0,0,0,1,0,0,0,0,0,0
48,2013-05-30,49,1,1,1,0,0,0,0,1,1,0,1,1
49,2013-05-30,50,0,0,1,1,1,0,0,0,0,0,0,0
50,2013-05-30,51,0,1,1,0,0,1,0,0,0,0,0,0
51,2013-07-17,52,0,1,1,0,0,1,1,0,0,0,1,1
52,2013-07-17,53,0,0,0,1,0,0,0,1,1,0,0,0
53,2013-07-17,54,0,0,0,1,1,0,0,1,1,0,0,0
54,2013-09-24,55,1,0,0,0,0,0,0,0,0,0,0,0
55,2013-09-24,56,0,1,0,0,0,1,0,1,1,0,0,0
56,2013-09-24,57,0,0,0,0,1,0,1,1,1,1,1,0
57,2013-09-24,58,1,1,1,0,0,0,0,0,1,0,0,0
58,2013-09-24,59,1,0,0,0,0,1,1,0,0,0,0,1
59,2013-09-24,60,0,1,1,1,1,0,0,0,1,0,0,0
60,2013-12-29,61,0,0,0,1,1,0,0,0,0,0,1,1
61,2013-12-29,62,0,1,0,0,0,1,1,1,1,0,0,1
62,2014-01-12,63,0,1,0,0,0,0,0,0,0,0,0,0
63,2014-01-27,64,0,0,0,1,0,1,0,1,0,0,0,0
64,2014-01-27,65,0,1,1,1,1,0,0,0,0,1,0,0
65,2014-02-12,66,0,1,0,0,0,0,0,1,1,0,1,0
66,2014-02-12,67,1,0,0,0,0,0,0,1,1,0,0,1
67,2014-02-12,68,1,1,0,1,0,0,1,0,1,0,0,0
68,2014-02-12,69,1,0,0,0,0,0,0,0,0,0,0,0
69,2014-04-13,70,1,1,0,0,0,0,1,0,1,0,1,1
70,2014-04-13,71,1,0,0,0,1,1,1,0,0,0,0,0
71,2014-04-13,72,0,0,0,1,0,0,0,0,0,0,0,1
72,2014-04-13,73,1,1,1,0,0,1,0,0,1,0,1,0
73,2014-07-10,74,0,1,0,0,0,1,0,0,0,0,0,0
74,2014-10-11,75,0,1,1,1,1,0,0,0,1,0,1,1
75,2014-10-11,76,1,0,1,0,0,0,0,0,0,1,0,1
76,2014-10-11,77,0,0,0,0,1,1,0,0,0,1,1,0
77,2014-10-11,78,0,1,0,0,1,0,0,0,0,0,0,0
78,2014-11-19,79,0,0,1,0,0,1,0,0,0,0,0,0
79,2015-01-01,80,0,1,0,0,0,0,0,0,0,0,0,0
80,2015-01-13,81,1,1,1,1,0,1,0,0,0,0,0,1
81,2015-01-13,82,0,1,1,0,0,1,1,1,0,0,0,0
82,2015-01-13,83,1,1,1,1,1,1,0,0,0,1,0,1
83,2015-01-13,84,1,1,1,1,1,0,1,1,1,0,0,0
84,2015-01-13,85,1,0,1,0,1,0,0,0,1,1,1,0
85,2015-01-13,86,1,1,0,1,0,1,0,1,0,1,1,1
86,2015-01-13,87,1,0,0,0,0,0,0,1,1,0,1,1
87,2015-01-13,88,1,1,1,0,0,0,1,0,1,1,1,0
88,2015-01-13,89,1,1,0,0,1,1,0,0,0,1,1,1
89,2015-01-13,90,0,1,1,0,0,1,0,0,0,0,0,1
90,2015-02-01,91,0,0,0,1,1,0,0,0,0,0,1,0
91,2015-02-16,92,0,0,0,0,0,1,0,1,0,0,0,0
92,2015-05-17,93,0,1,0,0,0,1,0,0,0,0,0,0
93,2015-05-17,94,1,1,1,1,1,0,1,0,0,1,1,0
94,2015-05-17,95,1,1,0,0,1,1,0,1,1,0,0,0
95,2015-05-17,96,0,0,0,1,1,0,1,0,0,0,1,0
96,2015-05-17,97,1,1,1,1,1,0,0,0,1,0,1,1
97,2015-08-22,98,0,0,1,0,0,0,0,0,0,0,0,0
98,2015-09-25,99,1,1,0,1,1,1,1,1,0,0,1,0
99,2015-09-25,100,1,0,0,0,0,0,1,1,0,0,1,1
100,2015-09-25,101,0,0,0,0,0,0,1,1,0,0,1,1
101,2015-11-25,102,0,1,1,0,0,0,0,0,0,0,0,0
102,2015-12-15,103,1,0,0,1,0,0,0,1,1,0,0,1
103,2015-12-15,104,0,1,1,0,0,1,1,0,0,0,1,1
104,2015-12-15,105,1,0,0,1,1,0,1,1,1,0,0,1
105,2015-12-15,106,1,0,0,0,1,1,0,0,1,0,1,0
106,2015-12-15,107,0,1,1,1,1,0,0,0,0,1,1,0
107,2015-12-15,108,0,1,0,0,0,1,0,1,0,0,0,0
108,2015-12-15,109,1,0,0,0,0,1,0,1,1,0,0,1
109,2015-12-15,110,0,0,0,0,0,1,1,1,0,0,0,1
110,2015-12-15,111,1,0,1,1,0,0,1,1,1,0,1,0
111,2016-02-16,112,0,0,0,1,0,0,1,1,1,1,1,0
112,2016-02-16,113,1,0,0,1,1,0,1,0,0,1,0,0
113,2016-02-16,114,0,1,0,0,0,0,0,0,0,0,0,0
114,2016-02-16,115,0,0,0,1,1,0,0,1,1,1,1,1
115,2016-02-16,116,1,1,1,0,1,0,0,0,0,0,0,1
116,2016-02-16,117,0,1,0,1,0,0,0,1,1,0,0,0
117,2016-02-16,118,1,0,1,0,0,1,0,0,0,1,0,1
118,2016-02-16,119,1,0,1,1,0,0,0,0,1,0,1,1
119,2016-02-16,120,1,1,1,1,0,0,0,0,1,1,1,0
120,2016-02-16,121,1,1,1,0,1,0,1,1,0,0,0,0
121,2016-02-16,122,0,1,0,0,1,1,1,1,1,0,0,0
122,2016-05-21,123,0,1,1,0,0,0,0,0,0,0,0,0
123,2016-05-21,124,0,1,0,0,1,0,0,1,0,1,0,1
124,2016-05-21,125,0,0,0,1,1,1,0,1,1,0,0,0
125,2016-05-21,126,0,1,0,0,1,0,0,1,1,1,1,0
126,2016-05-21,127,1,0,1,1,1,0,1,1,0,0,1,0
127,2016-05-21,128,0,0,0,1,0,0,1,1,0,1,1,1
128,2016-05-21,129,1,1,0,0,0,1,1,0,1,0,0,1
129,2016-05-21,130,1,1,0,1,0,1,0,0,1,1,0,1
130,2016-05-21,131,0,1,0,0,0,1,0,1,1,0,1,0
131,2016-05-21,132,0,1,1,1,0,0,1,1,0,1,0,1
132,2016-05-21,133,0,0,0,1,1,0,0,1,0,1,1,0
133,2016-05-21,134,1,1,1,1,1,0,0,1,0,0,1,1
134,2016-05-21,135,0,0,0,1,1,0,1,1,0,0,0,0
135,2016-05-21,136,1,1,1,1,0,1,0,0,1,0,1,1
136,2016-08-08,137,1,0,0,0,0,0,0,0,0,0,0,0
137,2016-08-18,138,1,1,1,0,1,1,1,0,0,0,1,1
138,2016-08-18,139,1,0,0,0,0,1,1,1,0,1,1,0
139,2016-08-18,140,1,1,1,0,1,1,1,0,1,1,0,0
140,2016-08-18,141,0,1,1,1,1,1,1,0,0,0,1,0
141,2016-08-18,142,0,0,0,0,0,1,0,0,0,0,0,0
142,2016-08-18,143,0,1,0,0,0,0,1,0,1,1,0,0
143,2016-08-18,144,1,1,1,0,0,1,1,0,0,0,1,0
144,2016-08-18,145,1,1,1,0,1,0,1,0,0,1,0,0
145,2016-08-18,146,1,0,1,1,0,0,1,0,1,1,1,0
146,2016-08-18,147,1,0,0,1,1,1,0,0,0,1,0,1
147,2016-10-17,148,0,0,0,0,0,0,0,0,0,0,1,0
148,2016-10-17,149,0,0,0,0,0,1,1,0,1,0,1,1
149,2016-12-28,150,1,1,1,1,0,0,0,0,0,0,1,1
150,2016-12-28,151,1,0,0,0,0,0,0,0,0,0,0,0
151,2016-12-28,152,0,1,0,0,1,1,1,1,1,0,1,0
152,2017-01-20,153,0,1,1,1,1,0,0,0,1,1,1,1
153,2017-01-20,154,0,1,0,0,0,0,0,0,0,0,0,0
154,2017-03-13,155,1,0,0,1,1,0,1,0,1,1,0,0
155,2017-03-13,156,0,0,0,0,0,1,1,1,1,0,0,0
156,2017-03-13,157,0,1,0,1,1,1,1,0,1,0,0,1
157,2017-04-05,158,0,0,0,0,0,0,0,0,1,1,0,0
158,2017-04-05,159,1,0,0,0,1,0,0,0,0,1,1,0
159,2017-04-19,160,0,1,0,1,0,1,1,0,1,0,0,1
160,2017-04-19,161,0,0,0,0,1,1,0,0,1,0,0,1
161,2017-04-19,162,0,1,1,1,0,0,0,0,0,0,1,1
162,2017-04-19,163,0,0,0,0,0,0,0,1,0,0,1,0
163,2017-04-19,164,1,1,1,1,1,0,0,1,0,0,1,0
164,2017-04-19,165,1,1,1,1,1,0,0,1,0,1,0,1
165,2017-07-26,166,0,0,0,0,0,0,1,0,1,0,0,0
166,2017-07-26,167,0,0,0,1,1,1,1,1,1,0,1,1
167,2017-07-26,168,0,0,0,0,0,1,1,0,0,0,1,1
168,2017-10-18,169,0,0,0,0,0,0,0,0,0,1,0,0
169,2018-01-16,170,1,1,0,0,1,0,0,0,0,0,0,1
170,2018-01-16,171,1,0,0,1,0,1,1,1,1,0,0,0
171,2018-01-16,172,0,1,1,0,0,0,1,0,0,0,0,0
172,2018-01-16,173,1,1,1,0,1,0,1,0,1,0,0,1
173,2018-01-16,174,0,1,1,1,1,1,1,1,1,0,0,0
174,2018-01-16,175,0,0,0,1,0,1,1,0,0,1,0,0
175,2018-01-16,176,1,1,1,1,0,0,1,1,1,1,0,0
176,2018-01-16,177,1,1,0,0,0,1,0,1,1,0,1,0
177,2018-01-16,178,1,0,1,1,0,0,0,1,0,1,0,0
178,2018-01-16,179,0,1,1,1,0,1,0,0,1,0,1,1
179,2018-01-16,180,1,1,1,0,0,0,0,0,1,0,0,1
180,2018-01-16,181,0,1,1,1,0,0,0,1,0,0,1,0
181,2018-01-16,182,0,1,1,1,0,1,1,0,0,0,1,1
182,2018-01-16,183,0,0,0,1,1,0,0,0,0,0,1,0
183,2018-01-16,184,0,1,0,0,1,1,1,0,0,1,1,1
184,2018-02-19,185,1,0,0,0,0,0,0,0,0,1,0,0
185,2018-04-25,186,0,0,0,0,0,1,0,0,1,1,0,0
186,2018-04-25,187,0,1,0,0,1,1,1,0,1,1,0,0
187,2018-04-25,188,1,0,0,1,0,1,0,0,1,0,0,1
188,2018-07-27,189,1,1,0,0,1,0,1,0,1,0,0,1
189,2018-07-27,190,0,0,0,0,1,0,0,0,0,0,0,1
190,2018-07-27,191,1,0,0,0,0,0,1,0,0,1,1,0
191,2018-07-27,192,1,0,1,0,0,0,0,1,1,1,0,0
192,2018-07-27,193,1,0,0,1,1,0,0,1,0,0,0,0
193,2018-07-27,194,0,0,0,1,1,0,1,0,1,1,1,0
194,2018-07-27,195,1,1,1,1,0,1,0,0,1,0,1,1
195,2018-10-23,196,1,1,0,0,1,0,1,1,1,0,1,1
196,2018-10-23,197,1,0,0,0,0,0,0,0,0,0,0,1
197,2018-10-23,198,0,0,1,0,0,0,1,1,1,0,0,0
198,2018-10-23,199,0,1,0,0,0,0,0,0,0,0,0,0
199,2018-11-27,200,0,0,0,1,0,1,1,1,0,0,1,0
200,2019-01-29,201,0,0,0,0,0,1,0,0,0,0,0,0
201,2019-01-29,202,0,0,0,0,0,0,0,0,0,0,0,1
202,2019-04-25,203,0,0,0,0,0,1,0,0,0,0,0,0
203,2019-04-25,204,0,1,1,0,0,0,0,0,0,1,0,1
204,2019-07-22,205,1,0,0,1,1,1,1,0,0,1,1,0
205,2019-07-22,206,0,1,1,1,0,0,1,1,0,1,0,1
206,2019-07-22,207,0,0,0,1,1,1,0,0,0,0,0,1
207,2019-07-22,208,1,0,1,0,0,0,0,0,1,0,0,1
208,2019-07-22,209,0,1,0,1,0,1,0,1,0,1,0,0
209,2019-07-22,210,0,1,1,0,0,1,0,0,0,1,0,0
210,2019-07-22,211,1,1,1,0,1,1,0,1,0,0,1,1
211,2019-07-22,212,1,1,1,1,1,0,0,0,0,1,1,1
212,2019-07-22,213,1,1,0,0,1,1,0,1,1,1,0,1
213,2019-07-22,214,0,1,1,0,0,0,0,0,0,0,0,0
214,2019-07-22,215,1,1,1,1,1,1,0,0,0,0,0,1
215,2019-07-22,216,1,1,1,1,0,0,1,1,0,1,0,0
216,2019-10-23,217,0,0,0,0,0,0,1,0,0,0,0,0
217,2019-12-24,218,1,0,0,1,1,0,0,1,1,0,1,0
218,2019-12-24,219,1,1,0,0,0,1,0,1,1,1,1,1
219,2019-12-24,220,0,1,1,0,0,1,0,0,0,0,0,0
220,2019-12-24,221,0,0,0,1,1,0,1,1,0,1,1,1
221,2019-12-24,222,1,1,1,1,0,0,0,1,1,0,1,0
222,2019-12-24,223,1,0,0,0,1,0,0,0,0,1,0,1
223,2019-12-24,224,1,0,0,1,0,1,1,0,0,1,1,1
224,2019-12-24,225,0,0,0,1,1,1,0,1,0,1,1,0
225,2019-12-24,226,1,1,1,0,0,0,0,1,1,0,0,1
226,2020-02-03,227,1,0,0,0,0,0,1,1,0,1,1,0
227,2020-02-03,228,1,1,0,0,1,0,1,1,0,0,1,1
228,2020-04-04,229,0,1,1,0,0,1,1,0,0,0,0,0
229,2020-06-02,230,0,1,0,1,0,0,0,1,0,1,0,0
230,2020-06-02,231,1,0,0,1,1,0,0,0,0,0,1,0
231,2020-06-02,232,1,0,1,0,0,0,1,1,0,1,0,0
232,2020-09-04,233,1,1,1,0,1,1,0,0,1,0,0,1
233,2020-09-04,234,0,1,0,0,0,0,0,0,1,0,0,0
234,2020-10-26,235,1,1,0,1,1,0,1,1,1,1,0,0
235,2020-10-26,236,0,0,0,0,1,0,1,0,0,1,0,1
236,2020-10-26,237,0,1,0,1,0,0,0,0,0,0,0,1
237,2021-01-16,238,0,1,0,1,1,1,0,1,1,1,1,0
238,2021-01-16,239,1,1,1,1,0,0,1,1,1,1,0,0
239,2021-01-16,240,1,0,0,0,0,0,0,0,0,0,0,0
240,2021-01-16,241,1,0,0,1,1,1,0,1,1,1,0,1
241,2021-01-16,242,0,1,0,1,0,1,0,0,1,0,0,0
242,2021-01-16,243,0,0,0,0,1,1,1,1,1,0,1,1
243,2021-01-16,244,0,1,0,0,1,1,1,1,0,0,0,0
244,2021-01-16,245,1,1,0,1,1,1,0,0,1,1,0,1
245,2021-01-16,246,1,1,1,1,1,0,0,0,1,1,0,1
246,2021-02-25,247,0,1,1,1,0,1,1,0,1,1,0,0
247,2021-02-25,248,0,1,0,0,0,0,1,0,0,0,0,0
248,2021-03-21,249,0,1,0,1,0,0,1,1,0,0,0,0
249,2021-03-21,250,1,0,0,0,0,0,1,1,0,1,1,0
250,2021-03-21,251,0,1,1,0,0,1,1,0,0,1,0,0
251,2021-03-21,252,1,1,0,0,1,0,1,0,0,1,1,0
252,2021-03-21,253,1,0,0,1,0,0,0,0,0,1,0,0
253,2021-04-19,254,0,0,0,1,1,0,0,1,1,0,1,1
254,2021-04-19,255,0,0,0,1,1,0,0,0,0,0,0,0
255,2021-04-19,256,0,0,0,0,1,0,0,1,1,1,1,1
256,2021-04-19,257,0,1,0,1,1,1,0,0,1,0,1,1
257,2021-04-19,258,0,1,0,0,0,0,0,0,1,0,0,0
258,2021-07-08,259,0,0,0,1,0,1,0,1,1,1,1,0
259,2021-07-08,260,0,1,1,1,0,0,0,0,0,1,0,1
260,2021-07-08,261,1,1,1,0,1,0,1,0,0,1,0,0
261,2021-07-08,262,1,1,1,0,1,0,0,1,0,1,1,0
262,2021-07-08,263,1,1,0,1,0,0,0,0,0,0,1,1
263,2021-07-08,264,0,0,0,1,0,0,1,0,0,1,0,1
264,2021-07-08,265,1,1,1,1,0,0,0,0,0,0,0,0
265,2021-07-08,266,0,1,1,1,0,1,1,0,1,1,0,1
266,2021-07-08,267,0,1,1,0,0,1,0,0,1,0,1,0
267,2021-07-08,268,0,1,0,0,0,0,0,0,0,0,0,0
268,2021-07-08,269,1,1,0,0,0,1,0,1,1,0,1,1
269,2021-07-08,270,1,1,1,0,0,1,1,0,1,1,0,1
270,2021-07-08,271,1,1,1,0,1,1,1,1,0,0,0,0
271,2021-08-31,272,1,0,1,0,0,0,0,0,0,1,1,0
272,2021-08-31,273,0,0,0,0,0,0,0,1,1,0,0,0
273,2021-09-21,274,1,0,0,0,1,0,1,0,0,0,1,1
274,2021-10-17,275,0,1,1,0,0,1,1,1,1,0,1,0
275,2021-10-17,276,0,1,1,0,0,1,0,0,1,1,0,0
276,2021-12-31,277,1,0,0,0,0,0,0,0,0,0,1,1
277,2022-01-10,278,1,1,1,0,0,0,0,1,1,0,1,0
278,2022-01-10,279,0,1,1,0,0,1,0,1,0,1,0,0
279,2022-03-27,280,1,0,0,0,1,0,1,1,1,0,0,0
280,2022-03-27,281,1,0,0,0,0,0,0,0,0,0,1,1
281,2022-03-27,282,1,1,1,1,1,0,1,0,0,0,0,1
282,2022-03-27,283,0,1,1,0,0,1,1,0,1,1,0,1
283,2022-03-27,284,0,1,1,0,0,0,0,1,0,0,0,0
284,2022-03-27,285,1,1,1,0,1,0,1,0,1,0,0,0
285,2022-04-18,286,1,1,0,0,0,0,0,1,1,0,1,1
286,2022-04-18,287,1,0,0,0,1,1,1,1,1,0,0,0
287,2022-04-18,288,1,1,1,0,0,0,1,1,0,1,1,1
288,2022-04-18,289,1,1,0,0,1,1,0,0,0,0,0,0
289,2022-04-18,290,0,0,1,0,0,0,0,0,0,0,0,0
290,2022-04-18,291,1,0,0,1,0,0,0,0,0,0,0,0
291,2022-04-29,292,1,0,0,1,0,0,0,1,1,1,1,1
292,2022-04-29,293,0,1,1,0,0,0,1,0,1,0,0,0
293,2022-04-29,294,1,1,1,0,0,1,0,0,0,0,1,0
294,2022-05-30,295,1,1,1,0,1,1,0,0,0,1,0,0
295,2022-05-30,296,0,1,0,1,0,1,0,1,1,0,0,1
296,2022-05-30,297,0,1,1,0,0,0,1,1,1,1,1,1
297,2022-05-30,298,1,0,0,1,0,1,1,1,0,0,1,0
298,2022-05-30,299,0,0,1,0,0,1,0,1,1,0,0,1
299,2022-05-30,300,0,0,0,1,0,0,0,1,1,0,1,0
300,2022-05-30,301,1,1,1,0,0,0,0,1,0,0,1,1
301,2022-05-30,302,1,1,0,1,1,0,0,1,0,1,0,1
302,2022-05-30,303,1,0,1,0,0,0,1,0,1,0,0,0
303,2022-05-30,304,0,0,0,0,0,0,1,0,1,1,1,0
304,2022-05-30,305,0,1,0,0,0,0,1,1,1,0,1,1
305,2022-05-30,306,1,1,1,1,0,0,0,0,0,0,1,1
306,2022-05-30,307,1,1,1,0,0,0,0,1,1,1,1,0
307,2022-05-30,308,1,1,1,0,1,1,0,1,0,0,1,0
308,2022-05-30,309,0,0,1,0,1,0,1,1,0,0,0,0
309,2022-05-30,310,1,0,0,0,1,0,1,0,0,1,0,1
310,2022-05-30,311,0,1,1,1,0,1,0,0,0,0,1,0
311,2022-05-30,312,0,1,1,0,1,0,1,1,0,1,1,1
312,2022-05-30,313,1,1,1,1,1,1,0,0,0,0,1,0
313,2022-05-30,314,1,0,0,0,1,1,0,0,0,0,1,1
314,2022-05-30,315,0,1,0,0,1,1,1,0,0,1,0,1
315,2022-05-30,316,0,0,0,1,0,1,0,0,0,1,0,1
316,2022-05-30,317,1,1,1,0,0,0,1,1,0,1,0,0
317,2022-05-30,318,0,1,1,0,0,0,1,1,0,1,1,1
318,2022-05-30,319,0,1,0,1,0,1,1,0,1,1,1,1
319,2022-05-30,320,1,1,0,1,0,1,0,0,1,0,0,0
320,2022-05-30,321,1,0,0,1,1,1,1,1,1,0,0,0
321,2022-05-30,322,1,1,1,1,0,0,0,0,1,0,0,0
322,2022-05-30,323,0,1,1,1,0,0,1,1,0,1,1,0
323,2022-05-30,324,1,0,0,0,0,0,0,1,1,0,0,1
324,2022-05-30,325,0,1,0,0,0,0,0,1,1,0,0,1
325,2022-05-30,326,1,1,1,0,1,1,0,1,1,0,0,1
326,2022-05-30,327,0,1,1,1,0,1,0,1,1,0,0,0
327,2022-05-30,328,1,1,1,0,1,0,0,0,0,0,0,1
328,2022-05-30,329,1,1,0,0,0,0,0,1,1,0,0,0
329,2022-05-30,330,1,1,1,1,1,0,0,0,1,0,1,1
330,2022-05-30,331,1,1,0,1,0,0,0,1,0,0,1,1
331,2022-05-30,332,0,1,0,0,0,0,1,0,1,0,1,0
332,2022-05-30,333,1,0,1,0,0,0,0,1,0,1,0,0
333,2022-05-30,334,0,0,0,1,1,1,1,0,0,0,1,0
334,2022-05-30,335,1,1,1,1,1,0,1,1,1,0,0,0
335,2022-05-30,336,1,1,0,1,0,0,1,1,0,1,1,0
336,2022-05-30,337,1,1,1,0,0,1,0,1,1,1,0,0
337,2022-05-30,338,0,1,0,0,0,0,1,1,0,1,0,0
338,2022-05-30,339,1,0,0,1,0,1,0,1,1,0,0,0
339,2022-05-30,340,1,0,0,1,0,0,0,0,0,1,1,0
340,2022-05-30,341,0,1,0,1,1,0,1,1,0,1,1,1
341,2022-05-30,342,1,0,0,0,0,1,0,1,0,1,0,1
342,2022-05-30,343,1,1,1,0,0,1,1,0,0,0,0,0
343,2022-05-30,344,0,1,0,1,1,1,1,0,1,0,1,1
344,2022-05-30,345,0,1,1,1,0,1,1,0,0,1,1,1
345,2022-05-30,346,0,0,0,1,1,0,1,1,1,1,0,1
346,2022-05-30,347,1,0,0,1,0,1,1,0,1,0,1,1
347,2022-05-30,348,0,1,1,1,0,0,0,0,1,1,1,0
348,2022-05-30,349,1,1,0,1,1,1,0,0,1,0,0,0
349,2022-05-30,350,0,0,0,1,1,1,0,0,1,1,1,0
350,2022-05-30,351,0,0,0,1,1,1,0,1,1,0,0,1
351,2022-05-30,352,1,1,1,0,1,0,1,0,1,0,1,1
352,2022-05-30,353,1,1,1,0,1,0,0,1,1,0,1,0
353,2022-05-30,354,1,1,1,0,1,1,1,1,0,1,0,0
354,2022-05-30,355,1,1,0,1,1,0,0,1,0,1,0,1
355,2022-05-30,356,1,0,0,1,0,1,0,1,1,0,1,1
356,2022-05-30,357,1,0,1,1,1,0,1,0,1,0,1,1
357,2022-05-30,358,1,1,0,1,0,0,1,1,1,1,1,0
358,2022-05-30,359,1,1,0,1,0,1,0,0,1,1,0,1
359,2022-05-30,360,0,1,0,0,1,1,0,0,1,0,1,1
360,2022-05-30,361,0,0,0,1,0,1,0,1,1,0,0,1
361,2022-05-30,362,1,1,1,1,1,1,0,1,1,1,0,0
362,2022-05-30,363,0,1,0,1,0,0,1,0,0,0,1,0
363,2022-05-30,364,0,1,0,1,1,0,0,0,0,0,1,0
364,2022-05-30,365,0,1,1,0,0,1,0,0,0,0,0,1
365,2022-05-30,366,1,1,1,1,0,0,0,0,0,0,0,1
366,2022-05-30,367,1,1,1,1,0,1,1,0,0,0,0,1
367,2022-05-30,368,1,1,1,0,1,0,1,0,1,0,0,1
368,2022-05-30,369,0,1,1,0,1,0,0,1,0,0,0,1
369,2022-05-30,370,1,1,1,1,0,0,1,0,1,1,1,0
370,2022-05-30,371,1,1,0,1,0,0,0,0,1,0,0,0
371,2022-05-30,372,1,0,1,1,0,0,0,1,1,0,0,1
372,2022-05-30,373,1,1,0,1,0,0,0,0,0,1,1,0
373,2022-05-30,374,0,0,0,1,1,0,0,0,0,1,1,0
374,2022-05-30,375,1,1,1,0,1,0,0,1,1,1,1,0
375,2022-05-30,376,0,1,0,1,0,0,1,1,1,0,0,0
376,2022-05-30,377,0,1,1,0,1,0,1,1,0,0,1,0
377,2022-05-30,378,0,0,0,0,0,1,0,1,0,1,1,1
378,2022-05-30,379,1,0,0,0,1,0,0,0,0,0,0,1
379,2022-05-30,380,0,1,1,0,1,0,0,1,1,1,1,1
380,2022-05-30,381,0,0,1,1,0,0,1,0,1,1,0,0
381,2022-05-30,382,1,1,0,0,1,1,1,0,1,0,1,1
382,2022-08-26,383,0,0,0,0,0,1,0,0,0,0,0,0
383,2022-10-04,384,0,1,0,0,0,0,0,0,0,0,0,0
384,2022-11-16,385,0,0,0,0,0,0,0,1,0,0,0,0
385,2023-02-04,386,0,0,0,0,0,0,0,0,1,0,0,0
386,2023-05-14,387,0,0,0,0,0,0,0,0,0,1,0,0
387,2023-08-04,388,0,1,1,0,1,0,0,0,0,0,1,0
388,2023-08-04,389,1,0,0,0,0,0,0,0,0,0,1,0
389,2023-08-04,390,1,1,0,0,1,1,1,1,0,1,1,0
390,2023-08-04,391,0,1,0,0,0,0,0,0,0,0,0,0
391,2023-08-04,392,1,1,1,1,1,0,1,0,0,0,0,0
392,2023-08-04,393,0,1,0,0,0,1,1,0,0,0,0,1
393,2023-08-04,394,0,0,0,1,0,0,1,0,1,0,1,1
394,2023-08-04,395,1,0,0,0,1,1,0,0,0,0,1,1
395,2023-10-19,396,0,0,0,0,0,1,0,0,0,0,0,0
396,2023-11-20,397,0,0,1,0,0,0,0,0,0,0,0,0
397,2024-01-18,398,0,0,0,0,1,0,0,0,0,0,0,0
398,2024-04-15,399,0,0,0,0,0,1,0,0,0,0,0,0
399,2024-04-15,400,0,0,0,0,0,0,0,0,0,0,1,0
400,2024-04-30,401,0,1,0,1,1,0,0,1,0,1,1,1
401,2024-04-30,402,1,1,0,0,1,0,1,0,0,0,0,1
402,2024-04-30,403,0,0,0,1,1,1,1,0,0,0,0,0
403,2024-04-30,404,0,1,0,0,0,0,1,1,1,1,0,1
404,2024-04-30,405,1,1,1,0,1,1,0,0,0,0,0,0
405,2024-04-30,406,0,1,1,1,1,0,0,1,1,0,0,0
406,2024-04-30,407,0,1,0,1,0,1,0,1,0,1,0,1
407,2024-04-30,408,1,1,1,0,0,0,0,1,1,1,1,1
408,2024-04-30,409,1,1,1,1,1,0,1,1,0,0,0,1
409,2024-04-30,410,0,0,0,0,1,1,0,1,1,1,0,0
410,2024-04-30,411,1,1,0,0,0,1,1,1,0,0,1,1
411,2024-04-30,412,1,1,1,1,0,1,1,1,1,0,0,0
412,2024-04-30,413,1,1,0,0,0,0,0,0,0,1,1,0
413,2024-04-30,414,1,0,0,0,0,1,0,1,0,1,0,0
414,2024-04-30,415,0,1,1,0,0,1,1,0,0,1,0,1
415,2024-04-30,416,0,0,1,0,0,1,1,1,1,0,1,0
416,2024-04-30,417,1,1,1,1,0,1,0,0,0,0,0,1
417,2024-04-30,418,0,0,0,1,1,0,0,0,0,0,1,1
418,2024-04-30,419,0,0,1,0,1,0,1,0,1,0,1,0
419,2024-04-30,420,0,1,1,0,1,0,1,0,0,1,1,1
420,2024-04-30,421,1,1,1,1,0,0,0,0,0,0,0,1
421,2024-04-30,422,1,1,1,0,1,0,0,0,0,1,0,1
422,2024-04-30,423,0,1,1,0,0,1,1,1,0,0,0,0
423,2024-04-30,424,1,0,0,1,1,0,0,1,1,1,1,1
424,2024-04-30,425,1,0,0,0,1,1,1,1,0,0,1,1
425,2024-04-30,426,1,1,1,0,1,0,0,0,0,1,0,0
426,2024-04-30,427,0,1,0,1,0,1,1,0,0,0,0,0
427,2024-04-30,428,1,1,1,1,1,0,0,0,0,0,0,0
428,2024-04-30,429,0,0,0,0,0,0,1,0,0,1,1,1
429,2024-04-30,430,1,0,0,1,1,1,1,1,1,0,0,1
430,2024-04-30,431,1,1,1,0,0,0,0,1,1,1,0,1
431,2024-04-30,432,0,1,0,1,1,1,0,0,1,1,1,1
432,2024-04-30,433,1,0,0,1,1,0,0,0,0,1,0,0
433,2024-04-30,434,1,1,0,1,1,0,0,0,1,0,0,1
434,2024-04-30,435,0,1,1,0,0,1,1,1,1,0,1,1
435,2024-04-30,436,1,1,1,0,0,1,0,0,0,0,0,1
436,2024-04-30,437,0,0,0,1,0,0,1,0,1,1,1,0
437,2024-04-30,438,1,0,0,0,0,0,1,1,1,1,1,1
438,2024-04-30,439,1,1,0,0,0,0,1,0,0,0,0,1
439,2024-04-30,440,1,1,0,0,1,0,0,1,0,0,1,0
440,2024-04-30,441,0,1,0,1,0,1,0,1,1,1,1,1
441,2024-04-30,442,1,1,0,1,0,1,0,1,1,1,0,1
442,2024-04-30,443,1,0,0,0,0,1,1,0,0,0,1,1
443,2024-04-30,444,1,1,1,0,0,0,1,1,1,1,0,0
444,2024-04-30,445,1,1,0,0,1,1,0,0,1,0,1,0
445,2024-04-30,446,1,1,0,1,0,0,0,1,1,0,0,0
446,2024-04-30,447,0,0,0,1,1,1,1,0,1,1,0,1
447,2024-04-30,448,0,1,1,0,0,1,1,0,0,1,0,0
448,2024-04-30,449,1,0,0,1,0,0,0,1,0,1,1,0
449,2024-04-30,450,0,1,0,0,1,0,0,0,1,0,1,1
450,2024-04-30,451,0,1,0,0,1,1,0,0,0,1,0,0
451,2024-04-30,452,1,1,1,0,0,1,0,0,0,0,1,0
452,2024-04-30,453,1,1,1,1,1,1,1,1,0,0,0,0
453,2024-04-30,454,0,1,1,0,1,0,1,0,0,0,1,1
454,2024-04-30,455,0,1,1,0,0,0,0,1,0,0,1,0
455,2024-04-30,456,0,1,0,1,1,0,1,1,1,1,0,1
456,2024-04-30,457,0,0,0,0,0,0,1,0,0,1,1,1
457,2024-04-30,458,1,0,0,0,0,0,0,1,1,0,1,0
458,2024-04-30,459,1,1,1,0,0,0,0,0,0,0,0,1
459,2024-04-30,460,0,1,1,1,0,0,0,1,1,1,1,1
460,2024-04-30,461,1,1,1,1,1,1,0,0,0,0,1,0
461,2024-04-30,462,0,1,1,0,0,0,0,0,1,1,1,0
462,2024-04-30,463,0,1,0,1,1,1,1,1,0,0,1,1
463,2024-04-30,464,1,1,1,1,0,1,0,0,1,1,1,0
464,2024-04-30,465,0,0,0,1,1,1,1,0,1,1,0,1

# Menyimpan hasil ke file

In [4]:
final_df.to_csv('DataTransformasiTA.csv', index=False)
print("\nDataset transformasi sudah disimpan sebagai 'DataTransformasiTA.csv'")

Dataset transformasi sudah disimpan sebagai 'DataTransformasiTA.csv'